project_id = "acpkhbjgnlenjfiswftx"

[functions.generate-video]
verify_jwt = false

[functions.generate-script]
verify_jwt = false

[functions.video-status]
verify_jwt = false

[functions.scrape-property]
verify_jwt = false

[functions.generate-luma-batch]
verify_jwt = false

[functions.check-luma-batch]
verify_jwt = false

[functions.stitch-video]
verify_jwt = false
